sudo: false

language: node_js

# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against
node_js:
  - '4'
  - 'node'

env:
  global:
    - NODE_ENV=travisci

before_install:
  - npm install -g gulp

script: gulp build
